# Generated by Django 5.2.3 on 2025-06-24 09:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Capteur',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('piece', models.CharField(max_length=50)),
                ('nom', models.CharField(max_length=50, unique=True)),
                ('emplacement', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Donnee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horodatage', models.DateTimeField(db_index=True)),
                ('temperature', models.DecimalField(decimal_places=2, max_digits=5)),
                ('capteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sensors.capteur')),
            ],
            options={
                'unique_together': {('capteur', 'horodatage')},
            },
        ),
    ]
